---
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-database
---
# secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-database
type: Opaque
data:
  POSTGRES_USER: dGVzdA== # "test"
  POSTGRES_DB: Zmxhc2stc2VydmljZQ== # "flask-service"
  POSTGRES_PASSWORD: dGVzdEAxMjM= # test@123
---
# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres-database
  # labels:
  #   name: postgres-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres-database
  template:
    metadata:
      labels:
        component: postgres-database
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
              # name: postgresql-container-port
---
# service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-database
  # labels:
  #   name: postgresql
spec:
  ports:
    - port: 5432
  selector:
    component: postgres-database
---